notifications:
  email:
    on_success: never
    on_failure: always
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - g++-6
install:
  - pip install pylint
  - pip install coveralls
  - pip install .
  - cd test
  - mkdir target
  - make all
  - cd ..
script:
  - pylint canaries
  - nosetests
after_success:
  - coveralls
