notifications:
  email:
    on_success: never
    on_failure: always
matrix:
  include:
    - os: linux
      language: python
      python:
        - "3.8"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - g++-6
      before_install:
        - cd test
        - mkdir target
        - make all
        - cd ..
      install:
        - pip install pylint
        - pip install coveralls
        - pip install .
      after_success:
        - coveralls
    - os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
        - cd test
        - mkdir target
        - make all
        - cd ..
      install:
        - sudo python3 -m pip install pylint
        - sudo python3 -m pip install coverage
        - sudo python3 -m pip install nose
        - sudo python3 -m pip install .
    - os: windows
      language: sh
      before_install:
        - cd test
        - mkdir target
        - ./Make-msvc.bat
        - cd ..
        - choco install python --version=3.8.3
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install:
        - pip install pylint
        - pip install nose
        - pip install coverage
        - pip install .
script:
  - pylint canaries
  - nosetests
